//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhongKham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BACSI()
        {
            this.DATLICHes = new HashSet<DATLICH>();
        }
    
        public int BacSiID { get; set; }
        public string TenBS { get; set; }
        public int ChuyenKhoaID { get; set; }
        public System.DateTime NgaySinhBS { get; set; }
        public string GioiTinhBS { get; set; }
        public string SDTBS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATLICH> DATLICHes { get; set; }
        public virtual CHUYENKHOA CHUYENKHOA { get; set; }
    }
}
