//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhongKham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int CTDHID { get; set; }
        public Nullable<int> DonHangID { get; set; }
        public Nullable<int> GoiKhamID { get; set; }
        public Nullable<int> SoLuongSP { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual GOIKHAM GOIKHAM { get; set; }
    }
}
