//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhongKham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATLICH
    {
        public int DatLichID { get; set; }
        public string TenKH { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int ChuyenKhoaID { get; set; }
        public int BacSiID { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<System.TimeSpan> GioKham { get; set; }
        public int XetNghiemID { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual XETNGHIEM XETNGHIEM { get; set; }
    }
}
