//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhongKham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public int KetQuaID { get; set; }
        public int IDTK { get; set; }
        public string MaDon { get; set; }
        public string HinhAnh { get; set; }
        public string ChiTiet { get; set; }
        public string KetLuan { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
