//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhongKham.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.KETQUAs = new HashSet<KETQUA>();
        }

        public int IDTK { get; set; }
        public string TenUser { get; set; }
        [DataType(DataType.Password)]
        public string MatKhauUser { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinhKH { get; set; }
        public string GioiTinhKH { get; set; }
        public string DiaChiKH { get; set; }
        public string SDTKH { get; set; }
        [NotMapped]

        [Compare("MatKhauUser", ErrorMessage = "Mật khẩu không trùng khớp!")]
        [DataType(DataType.Password)]
        public string ConfirmPass { get; set; }
        public string ErrorLogin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA> KETQUAs { get; set; }
    }
}